In [1]:
import optuna

study = optuna.load_study(
    study_name='water_depth_to_discharge_seq2seq',
    storage='sqlite:///study.db',
)

/home/guilherme/.local/share/rtx/installs/python/3.11.4/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = study.trials_dataframe()
# Sort by best_validation_loss
df = df.sort_values(by='user_attrs_best_val_loss', ascending=True)

In [3]:
df

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_dense_activation_function,params_lstm_0_activation_function,params_lstm_0_bidirectional,params_lstm_0_units,...,params_lstm_2_activation_function,params_lstm_2_bidirectional,params_lstm_2_units,params_number_of_hidden_layers,params_return_sequences_last,user_attrs_best_training_loss,user_attrs_best_val_loss,user_attrs_number_of_parameters,system_attrs_nsga2:generation,state
74,74,0.002709,17757.0,2023-10-09 01:09:23.224211,2023-10-09 01:09:25.968669,0 days 00:00:02.744458,tanh,sigmoid,True,46,...,NaN,NaN,NaN,1,True,0.004749,0.002709,17757,1,COMPLETE
48,48,0.003069,19595.0,2023-10-09 01:07:35.316827,2023-10-09 01:07:39.285486,0 days 00:00:03.968659,sigmoid,linear,True,23,...,NaN,NaN,NaN,2,True,0.004528,0.003069,19595,0,COMPLETE
77,77,0.003233,291.0,2023-10-09 01:09:32.150341,2023-10-09 01:09:36.860860,0 days 00:00:04.710519,sigmoid,tanh,True,5,...,NaN,NaN,NaN,1,True,0.010611,0.003233,291,1,COMPLETE
40,40,0.004442,770.0,2023-10-09 01:06:52.981594,2023-10-09 01:06:56.219724,0 days 00:00:03.238130,sigmoid,sigmoid,False,8,...,NaN,NaN,NaN,1,False,0.015993,0.004442,770,0,COMPLETE
21,21,0.004653,11413.0,2023-10-09 01:04:54.914947,2023-10-09 01:04:59.269307,0 days 00:00:04.354360,tanh,sigmoid,False,6,...,NaN,NaN,NaN,2,True,0.005956,0.004653,11413,0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,81,0.046929,346.0,2023-10-09 01:09:51.974068,2023-10-09 01:09:53.706443,0 days 00:00:01.732375,relu,relu,False,4,...,NaN,NaN,NaN,1,False,0.006736,0.046929,346,1,COMPLETE
65,65,0.047713,3242.0,2023-10-09 01:08:41.548113,2023-10-09 01:08:44.747877,0 days 00:00:03.199764,relu,linear,True,14,...,NaN,NaN,NaN,1,False,0.006904,0.047713,3242,1,COMPLETE
32,32,0.063438,11649.0,2023-10-09 01:06:11.573774,2023-10-09 01:06:15.511556,0 days 00:00:03.937782,relu,linear,True,33,...,NaN,NaN,NaN,2,True,0.010409,0.063438,11649,0,COMPLETE
17,17,0.063438,911.0,2023-10-09 01:04:33.474340,2023-10-09 01:04:35.232294,0 days 00:00:01.757954,relu,linear,False,14,...,NaN,NaN,NaN,1,True,0.010409,0.063438,911,0,COMPLETE
0,0,0.063438,120829.0,2023-10-09 01:02:55.310897,2023-10-09 01:03:01.790791,0 days 00:00:06.479894,relu,sigmoid,True,57,...,sigmoid,False,36.0,3,True,0.010409,0.063438,120829,0,COMPLETE

In [5]:
row = df.iloc[0]
display(row)

number                                                       74
values_0                                               0.002709
values_1                                                17757.0
datetime_start                       2023-10-09 01:09:23.224211
datetime_complete                    2023-10-09 01:09:25.968669
duration                                 0 days 00:00:02.744458
params_dense_activation_function                           tanh
params_lstm_0_activation_function                       sigmoid
params_lstm_0_bidirectional                                True
params_lstm_0_units                                          46
params_lstm_1_activation_function                           NaN
params_lstm_1_bidirectional                                 NaN
params_lstm_1_units                                         NaN
params_lstm_2_activation_function                           NaN
params_lstm_2_bidirectional                                 NaN
params_lstm_2_units                                         NaN
params_number_of_hidden_layers                                1
params_return_sequences_last                               True
user_attrs_best_training_loss                          0.004749
user_attrs_best_val_loss                               0.002709
user_attrs_number_of_parameters                           17757
system_attrs_nsga2:generation                                 1
state                                                  COMPLETE
Name: 74, dtype: object